pipeline {
        agent {
        docker { image 'python:2.7.16-slim'
	       args '--user root'
        }
    }
    stages {
        stage('build') {
            when {
              changeset "**/vote/**"
	    }
            steps {
                echo 'compilling vote app!!'
		dir ('vote'){
                sh 'pip install -r requirements.txt '
		}
            }
        }
        stage('test') {
            when {
              changeset "**/vote/**"
	    }
            steps {
                echo 'Running unit tests on vote app'
                dir ('vote'){
                sh 'nosetests -v'
                }
	  }
        }

        stage('package-docker') {
             agent any
             when {
              changeset "**/vote/**"
              branch 'master'
             }
            steps {
                echo 'Packaging vote app with docker '
            script {
                docker.withRegistry('https://registry-1.docker.io/v2/', 'dockerlogin'){
                def workerImage = docker.build("hutinskit/vote:v${env.BUILD_ID}", "./vote")
                workerImage.push()
                workerImage.push("${env.BRANCH_NAME}")
                }
            }

            }
        }
    }

    post {
        always {
            echo 'Pipeline for worker is completed.'
        }
    }


}
