pipeline {
    agent none

    stages {
        stage('build') {
        agent {
	docker {
        image 'maven:3.8.1-adoptopenjdk-11'
        args  '-v $HOME/.m2:/root/.m2'
       }
       }
            steps {
                echo 'compiling worker app!'
		dir ('worker'){
                sh ' mvn compile'
		}
            }
        }
        stage('test'){
        agent {
	docker {
        image 'maven:3.8.1-adoptopenjdk-11'
        args  '-v $HOME/.m2:/root/.m2'
        }
	}
            steps {
                echo 'Running unit tests'
                dir ('worker'){
                sh 'mvn clean test'
                }
	  }
        }
        stage('package') {
            when {
	      branch 'mester'
	    }
        agent {
	docker {
        image 'maven:3.8.1-adoptopenjdk-11'
        args  '-v $HOME/.m2:/root/.m2'
	}
	}
            steps {
                echo 'Packaging worker app'
                dir ('worker'){
		sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
        stage('package-docker') {
             agent any
            steps {
                echo 'Packaging worker app with docker hehe'
    script {
		docker.withRegistry('https://registry-1.docker.io/v2/', 'dockerlogin'){
		def workerImage = docker.build("hutinskit/worker:v${env.BUILD_ID}", "./worker")
		workerImage.push()

		}
    }

            }
        }
}
    post {
        always {
            echo 'Pipeline for worker is completed.'
        }
    }


}
